-- Create system_settings table
CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create bot_logs table
CREATE TABLE IF NOT EXISTS bot_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'warning')),
  region TEXT NOT NULL,
  articles_count INTEGER DEFAULT 0,
  log_message TEXT,
  metadata JSONB
);

-- Create reporters table
CREATE TABLE IF NOT EXISTS reporters (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('AI Bot', 'Human')),
  region TEXT,
  status TEXT DEFAULT 'Active',
  avatar_icon TEXT, -- 이모지 또는 URL
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reporters ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users full access (for admin dashboard)
CREATE POLICY "Allow all access to authenticated users" ON system_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to authenticated users" ON bot_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to authenticated users" ON reporters FOR ALL TO authenticated USING (true) WITH CHECK (true);
